# Generated by Django 5.1.7 on 2025-03-28 00:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_game', to='games.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('cover', models.ImageField(blank=True, null=True, upload_to='game_covers/')),
                ('rating', models.FloatField(default=0)),
                ('total_votes', models.IntegerField(default=0)),
                ('torrent_file', models.FileField(blank=True, null=True, upload_to='torrents/')),
                ('direct_link', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('Action', 'Action'), ('RPG', 'RPG'), ('Strategy', 'Strategy')], max_length=100)),
                ('favorites', models.ManyToManyField(blank=True, related_name='comments_favorite_games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_ratings', to='games.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_ratings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
